version: '3.8'

services:
  app:
    build: .
    container_name: Sprint_app
    ports:
      - "8080:80"
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USERNAME=root
      - DB_PASSWORD=secret
      - DB_DATABASE=sprint_db
      - APP_ENV=local
      - APP_DEBUG=true
    depends_on:
      - db
    volumes:
      - .:/var/www/html
    networks:
      - Sprint_network

  db:
    image: mysql:8.0
    container_name: Sprint_app_db
    restart: always
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=sprint_db
    volumes:
      - db_data:/var/lib/mysql
      - ./sql/create_database_and_tables.sql:/docker-entrypoint-initdb.d/create_database_and_tables.sql
    networks:
      - Sprint_network

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    restart: always
    depends_on:
      - db
    ports:
      - "8090:80"
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
      - PMA_USER=root
      - PMA_PASSWORD=secret
    networks:
      - Sprint_network

volumes:
  db_data:

networks:
  Sprint_network:
    driver: bridge
